#!/usr/bin/env bash
# =============================================================================
# 3-adapt-skills.sh
# Run this after your DDD Skills are complete.
#
# Reads each SKILL.md from ~/skills-source/ and writes it into the correct
# location / format for each of the 4 agents:
#
#   Claude Code  →  .claude/skills/<name>/SKILL.md          (native format)
#   Codex        →  ~/.agents/skills/<name>/SKILL.md         (native format)
#                   AGENTS.md at repo root                   (inline concat)
#   Copilot      →  .github/copilot-instructions.md          (inline concat)
#   Gemini CLI   →  GEMINI.md at repo root                   (inline concat)
#
# Also symlinks DDD Skills (when present in skills-source) into the same dirs.
#
# Usage:
#   bash ~/3-adapt-skills.sh [--repo /path/to/repo] [--skills-src /path/to/skills]
# =============================================================================

set -euo pipefail

# ── Defaults (override with flags) ───────────────────────────────────────────
REPO_DIR="${REPO:-$HOME/quarkusinsights051826}"
SKILLS_SRC="${SKILLS_SRC:-$HOME/skills-source}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)       REPO_DIR="$2"; shift 2 ;;
    --skills-src) SKILLS_SRC="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

log()  { echo -e "\n\033[1;34m==> $*\033[0m"; }
step() { echo "  • $*"; }

# ── Skill repos to process (general-purpose; add DDD repos when ready) ───────
SKILL_NAMES=(
  "quarkus-skill-testing"
  "quarkus-skill-persistence"
  "quarkus-skill-rest"
  "quarkus-skill-logging"
)

# When your DDD Skills repos exist, add them here:
# DDD_SKILL_NAMES=(
#   "quarkus-skill-ddd-aggregates"
#   "quarkus-skill-ddd-valueobjects"
#   "quarkus-skill-ddd-ports"
# )
ALL_SKILLS=("${SKILL_NAMES[@]}")

# ─────────────────────────────────────────────────────────────────────────────
# Helper: strip YAML frontmatter from a SKILL.md and return just the body
# (The frontmatter is for agent trigger logic; the body is the actual guidance)
# ─────────────────────────────────────────────────────────────────────────────
extract_body() {
  local file="$1"
  # If file starts with ---, skip until the second ---
  if head -1 "$file" | grep -q '^---'; then
    awk 'BEGIN{found=0} /^---/{found++; if(found==2){found=99; next}} found==99{print}' "$file"
  else
    cat "$file"
  fi
}

extract_frontmatter_field() {
  local file="$1" field="$2"
  awk "/^$field:/{print; exit}" "$file" | sed "s/^$field: *//"
}

# =============================================================================
log "Validating paths"
# =============================================================================
[ -d "$REPO_DIR" ] || { echo "ERROR: repo not found at $REPO_DIR"; exit 1; }
[ -d "$SKILLS_SRC" ] || { echo "ERROR: skills-source not found at $SKILLS_SRC"; exit 1; }

CLAUDE_SKILLS="$REPO_DIR/.claude/skills"
AGENTS_SKILLS="$HOME/.agents/skills"
COPILOT_FILE="$REPO_DIR/.github/copilot-instructions.md"
GEMINI_FILE="$REPO_DIR/GEMINI.md"
AGENTS_FILE="$REPO_DIR/AGENTS.md"

mkdir -p "$CLAUDE_SKILLS" "$AGENTS_SKILLS" "$REPO_DIR/.github"

# =============================================================================
log "Building per-agent instruction files"
# =============================================================================

# Start fresh for the concatenated files
cat > "$COPILOT_FILE" << 'HDR'
# GitHub Copilot Instructions
<!-- Auto-generated by 3-adapt-skills.sh — do not edit by hand -->

You are building a Quarkus application following Domain-Driven Design (DDD)
and Hexagonal Architecture. The rules below are non-negotiable. Follow them
exactly, do not rationalise exceptions.

HDR

cat > "$GEMINI_FILE" << 'HDR'
# Gemini CLI Instructions
<!-- Auto-generated by 3-adapt-skills.sh — do not edit by hand -->

You are building a Quarkus application following Domain-Driven Design (DDD)
and Hexagonal Architecture. The rules below are non-negotiable. Follow them
exactly, do not rationalise exceptions.

HDR

cat > "$AGENTS_FILE" << 'HDR'
# Codex Agent Instructions
<!-- Auto-generated by 3-adapt-skills.sh — do not edit by hand -->

You are building a Quarkus application following Domain-Driven Design (DDD)
and Hexagonal Architecture. The rules below are non-negotiable. Follow them
exactly, do not rationalise exceptions.

HDR

# =============================================================================
# Process each skill
# =============================================================================
for skill_name in "${ALL_SKILLS[@]}"; do
  skill_dir="$SKILLS_SRC/$skill_name"
  skill_file="$skill_dir/SKILL.md"

  if [ ! -f "$skill_file" ]; then
    echo "  SKIP: $skill_name — SKILL.md not found at $skill_file"
    continue
  fi

  step "Processing $skill_name"

  title=$(extract_frontmatter_field "$skill_file" "name" 2>/dev/null \
          || echo "$skill_name")
  body=$(extract_body "$skill_file")

  # ── Claude Code: copy SKILL.md verbatim (native format, frontmatter intact)
  dest_claude="$CLAUDE_SKILLS/$skill_name"
  mkdir -p "$dest_claude"
  cp "$skill_file" "$dest_claude/SKILL.md"
  step "  Claude Code  → .claude/skills/$skill_name/SKILL.md"

  # ── Codex: same format, goes to ~/.agents/skills/ (global, pre-loaded)
  dest_agents="$AGENTS_SKILLS/$skill_name"
  mkdir -p "$dest_agents"
  cp "$skill_file" "$dest_agents/SKILL.md"
  step "  Codex        → ~/.agents/skills/$skill_name/SKILL.md"

  # ── Codex inline: also append body to AGENTS.md at repo root
  {
    echo ""
    echo "---"
    echo "## ${title}"
    echo ""
    echo "$body"
    echo ""
  } >> "$AGENTS_FILE"
  step "  Codex        → AGENTS.md (appended)"

  # ── Copilot: append body (no frontmatter) to copilot-instructions.md
  {
    echo ""
    echo "---"
    echo "## ${title}"
    echo ""
    echo "$body"
    echo ""
  } >> "$COPILOT_FILE"
  step "  Copilot      → .github/copilot-instructions.md (appended)"

  # ── Gemini CLI: append body to GEMINI.md
  {
    echo ""
    echo "---"
    echo "## ${title}"
    echo ""
    echo "$body"
    echo ""
  } >> "$GEMINI_FILE"
  step "  Gemini CLI   → GEMINI.md (appended)"

done

# =============================================================================
log "Add SPEC.md reference to all agent instruction files"
# =============================================================================
# Each agent must read SPEC.md as the ground truth for what to build.
# Appending this ensures the agents look for it.

SPEC_NOTE='
---
## Specification

Read `SPEC.md` in the repository root. This is the single source of truth for
the application you must build. Do not ask for clarification — implement
everything described in SPEC.md exactly as written.
'

echo "$SPEC_NOTE" >> "$COPILOT_FILE"
echo "$SPEC_NOTE" >> "$GEMINI_FILE"
echo "$SPEC_NOTE" >> "$AGENTS_FILE"

# Claude Code already sees SPEC.md through the CLAUDE.md project context;
# create/update CLAUDE.md to reference it explicitly.
cat > "$REPO_DIR/CLAUDE.md" << 'CLAUDEMD'
# Claude Code Project Context

You are building a Quarkus application following Domain-Driven Design (DDD)
and Hexagonal Architecture.

## Specification

Read `SPEC.md`. It is the single source of truth for what you must build.
Do not ask for clarification — implement everything described in SPEC.md exactly.

## Skills

The following skills are active for this project. They are loaded automatically
from `.claude/skills/`. Read and follow every rule in each skill.

CLAUDEMD

for skill_name in "${ALL_SKILLS[@]}"; do
  echo "- ${skill_name}" >> "$REPO_DIR/CLAUDE.md"
done

step "Claude Code  → CLAUDE.md"

# =============================================================================
log "Done. File summary:"
# =============================================================================
echo ""
echo "  Claude Code:"
echo "    $REPO_DIR/CLAUDE.md"
for skill_name in "${ALL_SKILLS[@]}"; do
  echo "    $CLAUDE_SKILLS/$skill_name/SKILL.md"
done

echo ""
echo "  Codex:"
echo "    $AGENTS_FILE"
for skill_name in "${ALL_SKILLS[@]}"; do
  echo "    $AGENTS_SKILLS/$skill_name/SKILL.md"
done

echo ""
echo "  Copilot:"
echo "    $COPILOT_FILE"

echo ""
echo "  Gemini CLI:"
echo "    $GEMINI_FILE"

echo ""
echo "  When your DDD Skills are ready, add them to the ALL_SKILLS array at"
echo "  the top of this script and re-run — it's idempotent."
echo ""
echo "  Next: write SPEC.md, then launch agents with:"
echo "    bash ~/demo-layout.sh"
