# Log SQL during dev for the live-coding refactor demo.
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.show_sql=true
%dev.quarkus.hibernate-orm.format_sql=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
